name: contact_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.3
  hive: ^2.2.3
  stacked: ^3.4.0
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  stacked_services: ^1.1.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

